DROP TRIGGER IF EXISTS сеансы_до_премьеры_запрещены ON "Сеансы";
DROP TRIGGER IF EXISTS награды_до_премьеры_запрещены ON "Награды";
DROP TRIGGER IF EXISTS оценки_до_премьеры_запрещены ON "Оценки";
DROP TABLE Фильмы_Группы;
DROP TABLE Фильмы_Жанры;
DROP TABLE Билеты;
DROP TABLE Сеансы;
DROP TABLE Роли;
DROP TABLE Группы;
DROP TABLE Награды;
DROP TABLE Оценки;
DROP TABLE Медиа;
DROP TABLE Фильмы;
DROP TABLE Пользователи;
DROP TABLE Люди;
DROP TABLE Жанры;
DROP TABLE Места;
DROP TABLE Залы;
DROP TABLE Кинотеатры;
DROP TABLE Сети;